# Generated by Django 3.2.5 on 2021-08-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_person_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='member.person'),
        ),
    ]
