# Generated by Django 3.2.12 on 2022-04-05 09:21

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0004_alter_authuser_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phone_field.models.PhoneField(
                max_length=31, null=True, verbose_name='Phone'
            ),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phone_field.models.PhoneField(
                blank=True, max_length=31, null=True, verbose_name='Phone'
            ),
        ),
    ]
