# Generated by Django 3.2.12 on 2022-04-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20220405_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_person_role',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_person',
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_role', models.CharField(blank=True, max_length=50, null=True, verbose_name='person role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.organization', verbose_name='organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_person',
            field=models.ManyToManyField(through='member.OrganizationContact', to='member.Person', verbose_name='contact person'),
        ),
    ]
