# Generated by Django 3.2.9 on 2022-05-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20220405_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.person', verbose_name='Contact person'),
        ),
    ]
