# Generated by Django 3.2.9 on 2024-04-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20240414_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='onboarding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='member.onboarding', verbose_name='Onboarding group'),
        ),
    ]
