# Generated by Django 3.2.25 on 2024-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_authuser_password_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='agreed_terms',
            field=models.BooleanField(default=False),
        ),
    ]
