# Generated by Django 3.2.25 on 2024-06-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0010_authuser_agreed_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='onboarding',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='persons',
                to='member.onboarding',
                verbose_name='Onboarding group',
            ),
        ),
    ]
