# Generated by Django 3.2.25 on 2024-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_person_onboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='invite_sent',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='all_sent',
            field=models.BooleanField(default=False, verbose_name='All invites sent'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Reference name'),
        ),
    ]
