# Generated by Django 3.2.25 on 2024-08-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0012_auto_20240605_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='beneficiary_description',
            field=models.TextField(blank=True, verbose_name='Beneficiary description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='equipment_description',
            field=models.TextField(blank=True, verbose_name='Equipment description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_equipment_point',
            field=models.BooleanField(default=False, verbose_name='Is Equipment Point'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_beneficiary',
            field=models.BooleanField(default=False, verbose_name='Is Beneficiary'),
        ),
    ]
