# Generated by Django 3.2.25 on 2024-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0013_auto_20240825_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='equipment_description',
            field=models.TextField(blank=True, verbose_name='Equipment point description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_beneficiary',
            field=models.BooleanField(
                default=False,
                help_text='Only check this box if the Organization is currently accepting fruit donations',
                verbose_name='Is Beneficiary',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_equipment_point',
            field=models.BooleanField(
                default=False,
                help_text='Only check this box if the equipment registered at this Organization is currenlty made available',
                verbose_name='Is Equipment Point',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street_number',
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name='Street number'
            ),
        ),
    ]
