# Generated by Django 3.2.25 on 2025-02-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20241126_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name'], 'verbose_name': 'neighborhood', 'verbose_name_plural': 'neighborhoods'},
        ),
    ]
