# Generated by Django 3.2.25 on 2025-07-14 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0017_auto_20250504_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={
                'ordering': ['date_joined'],
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
