# Generated by Django 3.2.25 on 2026-02-04 15:41

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0019_auto_20251128_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='longitude',
        ),
        migrations.AddField(
            model_name='organization',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
