# Generated by Django 4.2.28 on 2026-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0020_alter_org_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(
                blank=True, default='', max_length=50, verbose_name='Last name'
            ),
        ),
    ]
