# Generated by Django 4.2.30 on 2026-09-23 18:37

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_alter_person_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='beneficiary_description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='equipment_description',
        ),
        migrations.AddField(
            model_name='organization',
            name='beneficiary_description_en',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Beneficiary description (EN)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='beneficiary_description_fr',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Beneficiary description (FR)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_en',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Short description (EN)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_fr',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Short description (FR)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='equipment_description_en',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Equipment point description (EN)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='equipment_description_fr',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Equipment point description (FR)'),
        ),
    ]
