# Generated by Django 4.2.30 on 2026-09-23 18:37

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_alter_person_family_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='beneficiary_description',
            new_name='beneficiary_description_en',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='equipment_description',
            new_name='equipment_description_en'
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_en',
            field=django_quill.fields.QuillField(blank=True,
            verbose_name='Short description (en)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='beneficiary_description_en',
            field=django_quill.fields.QuillField(blank=True,
            verbose_name='Beneficiary description (en)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='equipment_description_en',
            field=django_quill.fields.QuillField(blank=True,
            verbose_name='Equipment point description (en)')
        ),
        migrations.AddField(
            model_name='organization',
            name='description_fr',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Short description (fr)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='beneficiary_description_fr',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Beneficiary description (fr)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='equipment_description_fr',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Equipment point description (fr)'),
        ),
    ]
