"""
Django settings for saskatoon project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/

"""

import os
from pathlib import Path
from typing import Any, Optional
from dotenv import load_dotenv, find_dotenv #type: ignore
import attr

# Load the environment variables from .env file. 
file = find_dotenv()
if file: load_dotenv(dotenv_path=file)

@attr.s(auto_attribs=True)
class SaskatoonSettings:

    TIME_ZONE: str
    SECRET_KEY: str

    DB_ENGINE: str
    DB_NAME: str
    DB_USER: str
    DB_PASSWORD: str
    DB_HOST: str
    
    DEBUG: bool = attr.ib(default=False, converter=lambda strval: strval.lower() in ['yes', 'true'])
    TESTING: bool = attr.ib(default=False, converter=lambda strval: strval.lower() in ['yes', 'true'])
    
    TEST_DB_ENGINE: Optional[str] = None
    TEST_DB_NAME: Optional[str] = None
    TEST_DB_USER: Optional[str] = None
    TEST_DB_PASSWORD: Optional[str] = None
    TEST_DB_HOST: Optional[str] = None

    def get(self, name: str) -> Any:
        if self.TESTING and hasattr(self, 'TEST_'+name):
            return getattr(self, 'TEST_'+name)
        return getattr(self, name)

saskatoonSettings = SaskatoonSettings(
    DEBUG           =os.getenv('SASKATOON_DEBUG') or 'no',
    SECRET_KEY      =os.getenv('SASKATOON_SECRET_KEY'),
    TIME_ZONE       =os.getenv('SASKATOON_TIME_ZONE') or 'UTC',

    DB_ENGINE       =os.getenv('SASKATOON_DB_ENGINE'),
    DB_NAME         =os.getenv('SASKATOON_DB_NAME'),
    DB_USER         =os.getenv('SASKATOON_DB_USER'),
    DB_PASSWORD     =os.getenv('SASKATOON_DB_PASSWORD'),
    DB_HOST         =os.getenv('SASKATOON_DB_HOST'),
    
    TESTING         =os.getenv('SASKATOON_TESTING') or 'no',
    TEST_DB_ENGINE  =os.getenv('SASKATOON_TEST_DB_ENGINE'),
    TEST_DB_NAME    =os.getenv('SASKATOON_TEST_DB_NAME'),
    TEST_DB_USER    =os.getenv('SASKATOON_TEST_DB_USER'),
    TEST_DB_PASSWORD=os.getenv('SASKATOON_TEST_DB_PASSWORD'),
    TEST_DB_HOST    =os.getenv('SASKATOON_TEST_DB_HOST'),
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = saskatoonSettings.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = saskatoonSettings.get('DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'leaflet',
    'sitebase',
    'member',
    'harvest',
    'rest_framework',
    'django_filters',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saskatoon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saskatoon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': saskatoonSettings.get('DB_ENGINE'),
        'NAME': saskatoonSettings.get('DB_NAME'),
        'USER': saskatoonSettings.get('DB_USER'),
        'PASSWORD': saskatoonSettings.get('DB_PASSWORD'),
        'HOST': saskatoonSettings.get('DB_HOST'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('fr',u'Français'),
    ('en',u'English'),
]

LOCALE_PATHS = [
    'harvest/locale/',
    'member/locale/',
    'sitebase/locale/',
    'saskatoon/locale/'
]

CSRF_COOKIE_SECURE = True

TIME_ZONE = saskatoonSettings.get('TIME_ZONE')

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

# CUSTOM STUFF

AUTH_USER_MODEL = "member.AuthUser"

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
   'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
   'PAGINATE_BY': 10,
   'DEFAULT_RENDERER_CLASSES': (
   'rest_framework.renderers.TemplateHTMLRenderer',
   'rest_framework.renderers.JSONRenderer',
)
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'

