#!/bin/bash

# Load initial fixtures from .json files

# automatically exit on error
set -e

# get script directory no matter where it's called from (doesn't work w/ symlinks)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

# migrate database in case it was not already done
../manage.py migrate --skip-checks

# initial sequence order does matter!
seq=(auth-group member-city \
     member-neighborhood \
     member-state \
     member-country \
     member-language \
     member-actor \
     member-person \
     member-organization \
     member-authuser \
     harvest-treetype \
     harvest-property \
     harvest-equipmenttype \
     harvest-equipment \
     harvest-harvest \
     harvest-harvestyield \
     harvest-comment \
     harvest-requestforparticipation )

ignore='saskatoon'

# fixtures defined in sequence
for fix in "${seq[@]}"
do
    echo "Loading $fix"
    ./loaddata $fix
    ignore+="\\|$fix"
done

# unused .json files
unused=$(ls *.json | sed "/$ignore/!d")
if [[ -n "$unused" ]]; then
    echo "Unused .json fixtures:"
    echo "$unused"
    exit 4
else
    echo 'No unused fixtures.'
fi
