# Generated by Django 3.2.12 on 2022-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickleader_instructions', models.TextField(blank=True, help_text='Steps to pick a leader', max_length=1000, null=True, verbose_name='Pickleader Instructions in English')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
    ]
