# Generated by Django 3.2.25 on 2026-01-28 03:27

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):
    dependencies = [
        ('sitebase', '0003_auto_20250525_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('question_en', models.CharField(max_length=255, verbose_name='Question (en)')),
                ('question_fr', models.CharField(max_length=255, verbose_name='Question (fr)')),
                ('answer_en', models.TextField(verbose_name='Answer (en)')),
                ('answer_fr', models.TextField(verbose_name='Réponse (fr)')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('volunteer_home', 'Volunteer Home'),
                    ('pickleader_home', 'Pickleader Home'),
                    ('terms_conditions', 'Terms & Conditions'),
                    ('privacy_policy', 'Privacy Policy'),
                    ('faq', 'FAQ'),
                ],
                default=None,
                max_length=20,
                null=True,
                unique=True,
                verbose_name='Page type',
            ),
        ),
        migrations.CreateModel(
            name='FAQList',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Ref. Name')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (en)')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (fr)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enabled')),
                (
                    'items',
                    sortedm2m.fields.SortedManyToManyField(
                        blank=True, help_text=None, to='sitebase.FAQItem', verbose_name='Items'
                    ),
                ),
            ],
            options={
                'verbose_name': 'FAQ List',
                'verbose_name_plural': 'FAQ Lists',
                'ordering': ['is_active', 'name'],
            },
        ),
    ]
