# Generated by Django 4.2.28 on 2026-05-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitebase", "0005_alter_pagecontent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("volunteer_home", "Volunteer Home"),
                    ("pickleader_home", "Pickleader Home"),
                    ("terms_conditions", "Terms & Conditions"),
                    ("privacy_policy", "Privacy Policy"),
                    ("faq", "FAQ"),
                    ("about_us", "About Us"),
                    ("about_values", "About Values"),
                    ("about_roles", "About Roles"),
                    ("property_thanks", "New Property Thanks"),
                ],
                default=None,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Page type",
            ),
        ),
    ]
