# Generated by Django 4.2.28 on 2026-05-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitebase", "0006_alter_pagecontent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home_intro", "Home Introduction"),
                    ("home_volunteer", "Home Volunteers"),
                    ("home_owner", "Home Tree Owners"),
                    ("home_beneficiary", "Home Beneficiaries"),
                    ("home_pickleader", "Home Pickleaders"),
                    ("about_us", "About Us"),
                    ("about_values", "About Values"),
                    ("about_roles", "About Roles"),
                    ("privacy_policy", "Privacy Policy"),
                    ("faq", "FAQ"),
                    ("property_thanks", "New Property Thanks"),
                    ("home_user", "Home Authenticated User"),
                    ("terms_conditions", "Terms & Conditions"),
                ],
                default=None,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Page type",
            ),
        ),
    ]
