# Generated by Django 4.2.28 on 2026-06-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitebase", "0007_alter_pagecontent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home_intro", "[Home] Introduction"),
                    ("home_volunteer", "[Home] Volunteers"),
                    ("home_owner", "[Home] Tree Owners"),
                    ("home_beneficiary", "[Home] Beneficiaries"),
                    ("home_pickleader", "[Home] Pickleaders"),
                    ("about_us", "[About] Us"),
                    ("about_values", "[About] Values"),
                    ("about_roles", "[About] Roles"),
                    ("privacy_policy", "Privacy Policy"),
                    ("faq", "FAQ"),
                    ("property_thanks", "New Property Thanks"),
                    ("guides_intro", "[Guides] Preamble"),
                    ("guides_adopt_harvest", "Guides - How to Adopt Harvest"),
                    ("guides_publish_calendar", "[Guides] How to Publish Calendar"),
                    ("guides_picker_selection", "[Guides] How to Select Pickers"),
                    ("guides_fruit_distribution", "[Guides] How to Distribute Fruits"),
                    ("guides_resources", "[Guides] Pickleader Resources"),
                    ("terms_conditions", "Terms & Conditions"),
                ],
                default=None,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Page type",
            ),
        ),
    ]
