# Generated by Django 3.2.3 on 2021-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='authorized',
            field=models.BooleanField(
                default=None,
                help_text='Harvest in this property has been authorized for the current season by its owner',
                null=True,
                verbose_name='Authorized for this season',
            ),
        ),
        migrations.AlterField(
            model_name='requestforparticipation',
            name='is_accepted',
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name='Accepted'
            ),
        ),
        migrations.AlterField(
            model_name='requestforparticipation',
            name='showed_up',
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name='Showed up'
            ),
        ),
    ]
