# Generated by Django 3.0.7 on 2021-02-19 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforparticipation',
            name='picker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Person', verbose_name='Requester'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='harvest.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Neighborhood', verbose_name='Neighborhood'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.State', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='property',
            name='trees',
            field=models.ManyToManyField(help_text='Select multiple fruit types if applicable. Unknown fruit type or colour can be mentioned in the additional comments at the bottom.', to='harvest.TreeType', verbose_name='Fruit tree/vine type(s)'),
        ),
        migrations.AddField(
            model_name='harvestyield',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Harvest', verbose_name='Harvest'),
        ),
        migrations.AddField(
            model_name='harvestyield',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Actor', verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='harvestyield',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.TreeType', verbose_name='Tree'),
        ),
        migrations.AddField(
            model_name='harvestimage',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='harvest.Harvest'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvest',
            name='equipment_reserved',
            field=models.ManyToManyField(blank=True, to='harvest.Equipment', verbose_name='Reserve equipment'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='pick_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pick leader'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='harvest.Property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='trees',
            field=models.ManyToManyField(to='harvest.TreeType', verbose_name='Fruit trees'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='harvest.Property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.EquipmentType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='harvest.Harvest', verbose_name='harvest'),
        ),
    ]
