# Generated by Django 3.2.3 on 2021-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_auto_20210525_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='owner_fruit',
            field=models.BooleanField(default=False, verbose_name='Owner want their share of fruits'),
        ),
        migrations.AlterField(
            model_name='property',
            name='fruits_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height of lowest fruits (meters)'),
        ),
    ]
