# Generated by Django 3.2.4 on 2021-07-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20210527_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treetype',
            options={'ordering': ['name'], 'verbose_name': 'tree type', 'verbose_name_plural': 'tree types'},
        ),
    ]
