# Generated by Django 3.2.5 on 2021-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('harvest', '0004_alter_treetype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pending_contact_name',
            field=models.CharField(
                blank=True,
                help_text='Name of the person to be contacted for confirmation',
                max_length=50,
                verbose_name='Contact name',
            ),
        ),
        migrations.AlterField(
            model_name='property',
            name='pending_contact_phone',
            field=models.CharField(
                blank=True,
                help_text='Phone number to be used for confirmation',
                max_length=50,
                verbose_name='Contact phone number',
            ),
        ),
    ]
