# Generated by Django 3.2.12 on 2022-04-03 21:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ('harvest', '0006_alter_equipment_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pending_contact_phone',
            field=phone_field.models.PhoneField(
                blank=True,
                help_text='Phone number to be used for confirmation',
                max_length=31,
                verbose_name='Contact phone number',
            ),
        ),
    ]
