# Generated by Django 3.2.12 on 2022-04-12 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvest', '0008_auto_20220406_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Content')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HarvestComment', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='harvest.harvest', verbose_name='harvest')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Content')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyComment', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_comment', to='harvest.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
