# Generated by Django 3.2.9 on 2023-09-08 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0009_auto_20220414_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforparticipation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many people are you?'),
        ),
    ]
