# Generated by Django 3.2.25 on 2024-04-13 04:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_alter_requestforparticipation_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='about',
            field=django_quill.fields.QuillField(blank=True, help_text='If any help is needed from volunteer pickers, please describe them here.', max_length=1000, null=True, verbose_name='Public announcement'),
        ),
    ]
