# Generated by Django 3.2.25 on 2024-09-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20240825_1909'),
        ('harvest', '0012_rename_name_equipmenttype_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='count',
            field=models.SmallIntegerField(default=1, verbose_name='Number available'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='name_en',
            field=models.CharField(default='', max_length=50, verbose_name='Name (en)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='member.actor', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name_fr',
            field=models.CharField(max_length=50, verbose_name='Nom (fr)'),
        ),
    ]
