# Generated by Django 3.2.25 on 2024-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('harvest', '0013_auto_20240902_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(
                blank=True, max_length=50, verbose_name='Description'
            ),
        ),
    ]
