# Generated by Django 3.2.25 on 2025-05-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20250504_1308'),
        ('harvest', '0019_bilingual_fruit_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='status',
            field=models.CharField(choices=[('orphan', 'Orphan'), ('adopted', 'Adopted'), ('pending', 'To be confirmed'), ('scheduled', 'Scheduled'), ('ready', 'Ready'), ('succeeded', 'Succeeded'), ('cancelled', 'Cancelled')], default='orphan', max_length=20, verbose_name='Harvest status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.neighborhood', verbose_name='Borough'),
        ),
    ]
