# Generated by Django 3.2.25 on 2025-05-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('harvest', '0020_auto_20250504_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestyield',
            name='harvest',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='yields',
                to='harvest.harvest',
                verbose_name='Harvest',
            ),
        ),
    ]
