# Generated by Django 3.2.25 on 2025-07-14 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('member', '0018_alter_authuser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvest', '0021_alter_harvestyield_harvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='pick_leader',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='harvests',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Pick leader',
            ),
        ),
        migrations.AlterField(
            model_name='requestforparticipation',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='requests',
                to='member.person',
                verbose_name='Requester',
            ),
        ),
    ]
