# Generated by Django 3.2.25 on 2025-12-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_alter_authuser_options'),
        ('harvest', '0022_auto_20250714_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.actor', verbose_name='Owner'),
        ),
    ]
