# Generated by Django 3.2.25 on 2025-11-28 19:14

import django.core.validators
from django.db import migrations, models
import sitebase.utils


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0022_auto_20250714_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestyield',
            name='total_in_lb',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.7976931348623157e+308), sitebase.utils.validate_is_not_nan], verbose_name='Weight (lb)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90), sitebase.utils.validate_is_not_nan], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180), sitebase.utils.validate_is_not_nan], verbose_name='Longitude'),
        ),
    ]
