# Generated by Django 3.2.25 on 2026-01-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0023_alter_property_owner'),
        ('harvest', '0023_auto_20251128_1414'),
    ]

    operations = [
    ]
