# Generated by Django 4.2.30 on 2026-08-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0024_alter_property_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
