# Generated by Django 4.2.30 on 2026-09-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0025_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='harvest.property', verbose_name='property'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='harvest.harvest', verbose_name='harvest'),
        ),
    ]
