# Generated by Django 4.2.30 on 2026-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0025_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Updated on'),
        ),
    ]
