# Generated by Django 4.2.30 on 2026-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0026_alter_comment_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on'),
        ),
    ]
