name: publish-pydoctor-apidocs
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pydoctor
      run: |
        python -m pip install -U pip tox

    - name: Generate documentation
      run: |

        # Run pydoctor build
        tox -e apidocs

    - name: Publish apidocs to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate apidocs"
